- name: Configure Host 
  hosts: myhosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

   - name: Fix DNS resolution (by pointing at Azure's DNS resolver)
     replace:
        path: /etc/resolv.conf   
        regexp: '127.0.0.53'             
        replace: '168.63.129.16'
     become: yes
  
   - name: Clone from GitHub
     git:
        repo: 'https://github.com/lizrice/learning-ebpf.git' 
        dest: '~/source'
        version: 'main'