- name: Configure Host 
  hosts: myhosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

   - name: Fix DNS resolution (by pointing at Azure's DNS resolver)
     replace:
        path: /etc/resolv.conf   
        regexp: '127.0.0.53'             
        replace: '168.63.129.16'
     become: yes
  
   - name: Clone from GitHub
     git:
        repo: 'https://github.com/Grunet/learning-ebpf.git' 
        dest: '~/source'
        version: 'main'

   - name: Update apt package cache
     apt:
        update_cache: yes
     become: yes
     # This task sometimes hangs the first time it runs (wasn't able to figure out why), so this is intended to make sure it works on the 2nd try
     # Timing out an inidivual task try and retrying it doesn't seem possible, see https://github.com/ansible/ansible-documentation/issues/881#issuecomment-1832602135
    #  register: result
    #  async: 30      # Timeout
    #  poll: 5        # Interval to periodically check for completion
    #  retries: 5     
    #  until: result.finished != 0  # Retry until the command exits successfully

   - name: Get the current kernel version
     command: uname -r
     register: kernel_version

    # Copied from https://github.com/lizrice/learning-ebpf/blob/main/learning-ebpf.yaml (not all are probably necessary)
   - name: Install specific packages
     apt:
        name:
          - apt-transport-https 
          - ca-certificates
          - curl
          - clang
          - llvm
          - jq
          - libelf-dev
          - libpcap-dev
          - libbfd-dev
          - binutils-dev
          - build-essential
          - make
          - linux-tools-common
          - linux-tools-{{ kernel_version.stdout }} 
          - bpfcc-tools
          - python3-pip
        state: present 
     become: yes
     # This task sometimes hangs the first time it runs (wasn't able to figure out why), so this is intended to make sure it works on the 2nd try
     # Timing out an inidivual task try and retrying it doesn't seem possible, see https://github.com/ansible/ansible-documentation/issues/881#issuecomment-1832602135
    #  register: result
    #  async: 30      # Timeout
    #  poll: 5        # Interval to periodically check for completion
    #  retries: 5     
    #  until: result.finished != 0  # Retry until the command exits successfully
